@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsImV4cCI6MTgyNDY5MjExOX0.UshlsV-AnNpMaodRSOBP94g4hct3nmXCz-iJeoOPxqo


### Get Me
GET http://0.0.0.0:8080/api/user-me
Authorization: Bearer {{token}}

### Get Videos
GET http://0.0.0.0:8080/api/videos
Authorization: Bearer {{token}}


### Get all post
GET http://0.0.0.0:8080/api/posts
Accept: application/json
Authorization: Bearer {{token}}


### Create a new post
POST http://0.0.0.0:8080/api/posts
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Need driver, Please help",
  "content": "Hello, this is an example post.",
  "images": [
    1,
    2
  ],
  "published": true
}
