@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2ZTEwMmNkYjE3YjVmYjY5MWIzOTgiLCJpYXQiOjE3NjUyMDQ0NTksImV4cCI6MTgyNTIwNDQ1OX0.BjlbV79nm9pdhtsasNRbbNp-CjmJ9PQ66HM0NZYCAq0

### Login
POST http://0.0.0.0:8080/api/signin
Content-Type: application/json

{
  "email": "vikas@gmail.com",
  "password": "password"
}

### Register
POST http://0.0.0.0:8080/api/register
Content-Type: application/json

{
  "name": "Vikas",
  "email": "vikas@gmail.com",
  "password": "password",
  "confirm_password": "password",
   "mobile": "password"
}

### Get Videos
GET http://0.0.0.0:8080/api/videos
Authorization: Bearer {{token}}

### Get POSTS
GET http://0.0.0.0:8080/api/posts
Authorization: Bearer {{token}}


### PostsCreate
POST http://0.0.0.0:8080/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Fresh Post",
  "content": "some content here",
  "imageIds": ["somaaskdjhfhasdf"]
}


### GET POST BY ID

GET http://0.0.0.0:8080/api/posts/6936e21420b56aa488f31ee2
Content-Type: application/json
Authorization: Bearer {{token}}

### UPDATE POSTS

PUT http://0.0.0.0:8080/api/posts/6936e21420b56aa488f31ee2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "New Updated Post",
  "content": "some content here",
  "imageIds": [1]
}


### DELETE POST
DELETE http://0.0.0.0:8080/api/posts/6936e21420b56aa488f31ee2
Content-Type: application/json
Authorization: Bearer {{token}}


# NEW ROUTEs